site_name: harborapi

repo_url: https://github.com/pederhan/harborapi
repo_name: pederhan/harborapi
edit_uri: edit/main/docs/

theme:
  name: "material"
  palette:
    scheme: slate
    primary: deep purple
    accent: orange
  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes

plugins:
  - search
  - autorefs
  - mkdocstrings:
      watch:
        - harborapi
      enable_inventory: true
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
          options:
            docstring_style: numpy
            members_order: source
            docstring_section_style: table
            show_source: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - index.md
  - "Usage":
      - usage/index.md
      - usage/getting-started.md
      - usage/creating-system-robot.md
      - usage/exceptions.md
      - usage/async-sync.md
      - usage/limit.md
      - usage/validation.md
      - usage/rich.md
      - "Extended functionality":
          - "usage/ext/index.md"
          - "usage/ext/artifact.md"
          - "usage/ext/api.md"
          - "usage/ext/report.md"
  - "Recipes":
      - recipes/index.md
      - "Artifacts":
          - recipes/artifacts/conc-artifact.md
          - recipes/artifacts/artifactowner.md
          - recipes/artifacts/artifact-vulns.md
      - "Repositories":
          - recipes/repos/conc-repo.md
      # - "Projects":
      #     - recipes/conc-project.md
  - "Endpoints":
      - endpoints/index.md
      - endpoints/artifacts.md
      - endpoints/auditlogs.md
      - endpoints/configure.md
      - endpoints/cveallowlist.md
      - endpoints/gc.md
      - endpoints/health.md
      - endpoints/ldap.md
      - endpoints/oidc.md
      - endpoints/ping.md
      - endpoints/projects.md
      - endpoints/projectmetadata.md
      - endpoints/quota.md
      - endpoints/registries.md
      - endpoints/replication.md
      - endpoints/repositories.md
      - endpoints/robots.md
      - endpoints/scan.md
      - endpoints/scanall.md
      - endpoints/scanners.md
      - endpoints/search.md
      - endpoints/statistics.md
      - endpoints/systeminfo.md
      - endpoints/users.md
      - endpoints/usergroups.md
  - "Reference":
      - reference/index.md
      - reference/auth.md
      - reference/client.md
      - reference/client_sync.md
      - reference/exceptions.md
      - reference/types.md
      - reference/utils.md
      - "harborapi.models":
          - reference/models/_models.md
          - reference/models/_scanner.md
          - reference/models/base.md
          - reference/models/models.md
          - reference/models/scanner.md
          - reference/models/buildhistory.md
          - reference/models/oidc.md
      - "harborapi.ext":
          - reference/ext/api.md
          - reference/ext/artifact.md
          - reference/ext/cve.md
          - reference/ext/report.md
